# -*- coding: utf-8 -*-
"""Pregunta18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBcCFQruJ_O9wZrXkzVfv00Fq-ZNA-n9
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from google.colab import files
import warnings
warnings.filterwarnings('ignore')

# Step 1: Upload Excel file
print("Please upload your Excel file containing DPI data")
uploaded = files.upload()

# Step 2: Read the Excel file
filename = list(uploaded.keys())[0]
try:
    df = pd.read_excel(filename)
except Exception as e:
    print(f"Error reading Excel file: {e}")
    print("Ensure the file is a valid Excel file")
    raise

# Step 3: Display available columns
print("\nAvailable columns in your Excel file:")
print(df.columns.tolist())

# Step 4: Prompt user for DPI column name
dpi_column = input("Enter the name of your DPI column (case-sensitive, e.g., 'MONEY'): ")

# Step 5: Prepare the data
try:
    # Verify DPI column exists
    if dpi_column not in df.columns:
        raise KeyError(f"Column '{dpi_column}' not found in the Excel file")

    # Ensure DPI column is numeric
    df[dpi_column] = pd.to_numeric(df[dpi_column], errors='coerce')
    if df[dpi_column].isna().any():
        print(f"Warning: Some values in '{dpi_column}' could not be converted to numbers. Dropping missing values.")
        df = df.dropna(subset=[dpi_column])

    # Count the number of valid data points
    data_count = len(df[dpi_column])
    print(f"\nNumber of valid data points in '{dpi_column}': {data_count}")

    # Calculate log DPI
    df['Log_DPI'] = np.log(df[dpi_column])

    # Create a simple numeric index (since date analysis is not needed)
    df.index = range(1, len(df) + 1)

    # Step 6: Visualize the time series
    plt.figure(figsize=(12,6))
    plt.plot(df['Log_DPI'])
    plt.title('Log DPI Over Time')
    plt.xlabel('Observation Number')
    plt.ylabel('Log DPI')
    plt.show()

    # Step 7: Stationarity test (Augmented Dickey-Fuller test)
    def adf_test(series):
        result = adfuller(series)
        print('ADF Statistic:', result[0])
        print('p-value:', result[1])
        print('Critical Values:', result[4])
        if result[1] <= 0.05:
            print("Series is stationary")
        else:
            print("Series is not stationary - differencing may be needed")

    print("\nStationarity Test Results:")
    adf_test(df['Log_DPI'])

    # Step 8: Plot ACF and PACF to determine p and q
    plt.figure(figsize=(12,4))
    plt.subplot(121)
    plot_acf(df['Log_DPI'], ax=plt.gca())
    plt.subplot(122)
    plot_pacf(df['Log_DPI'], ax=plt.gca())
    plt.show()

    # Calculate first difference if needed
    df['Log_DPI_diff'] = df['Log_DPI'].diff().dropna()
    adf_test(df['Log_DPI_diff'].dropna())

    # Step 9: Fit ARIMA model (using 1,1,1 as example)
    model = ARIMA(df['Log_DPI'], order=(1,1,1))
    results = model.fit()

    # Print model summary
    print("\nModel Summary:")
    print(results.summary())

    # Step 10: Generate forecasts
    forecast_steps = 12  # Forecast 12 periods ahead
    forecast = results.forecast(steps=forecast_steps)

    # Plot actual vs forecast
    plt.figure(figsize=(12,6))
    plt.plot(df['Log_DPI'], label='Actual')
    forecast_index = range(len(df) + 1, len(df) + forecast_steps + 1)
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.title('Log DPI: Actual vs Forecast')
    plt.xlabel('Observation Number')
    plt.ylabel('Log DPI')
    plt.legend()
    plt.show()

    # Calculate and print forecast values
    forecast_df = pd.DataFrame({'Forecast_Log_DPI': forecast}, index=forecast_index)
    print("\nForecast Values:")
    print(forecast_df)

    # Step 11: Calculate RMSE
    train_size = int(len(df) * 0.8)
    train, test = df['Log_DPI'][0:train_size], df['Log_DPI'][train_size:]
    model_test = ARIMA(train, order=(1,1,1))
    results_test = model_test.fit()
    predictions = results_test.forecast(steps=len(test))
    rmse = np.sqrt(np.mean((predictions - test) ** 2))
    print(f'\nRoot Mean Square Error (RMSE): {rmse}')

except KeyError as e:
    print(f"Error: {e}")
    print("Please check your column name and ensure it matches exactly (case-sensitive)")
except ValueError as e:
    print(f"Error: {e}")
    print("Please check if your DPI column contains valid numeric values")
except Exception as e:
    print(f"Unexpected error: {e}")
    print("Please verify your Excel file format and data")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from google.colab import files
import warnings
warnings.filterwarnings('ignore')

# Step 1: Upload Excel file
print("Please upload your Excel file containing DPI data")
uploaded = files.upload()

# Step 2: Read the Excel file
filename = list(uploaded.keys())[0]
try:
    df = pd.read_excel(filename)
except Exception as e:
    print(f"Error reading Excel file: {e}")
    print("Ensure the file is a valid Excel file")
    raise

# Step 3: Display available columns
print("\nAvailable columns in your Excel file:")
print(df.columns.tolist())

# Step 4: Prompt user for DPI column name
dpi_column = input("Enter the name of your DPI column (case-sensitive, e.g., 'MONEY'): ")

# Step 5: Prepare the data
try:
    # Verify DPI column exists
    if dpi_column not in df.columns:
        raise KeyError(f"Column '{dpi_column}' not found in the Excel file")

    # Ensure DPI column is numeric
    df[dpi_column] = pd.to_numeric(df[dpi_column], errors='coerce')
    if df[dpi_column].isna().any():
        print(f"Warning: Some values in '{dpi_column}' could not be converted to numbers. Dropping missing values.")
        df = df.dropna(subset=[dpi_column])

    # Count the number of valid data points
    data_count = len(df[dpi_column])
    print(f"\nNumber of valid data points in '{dpi_column}': {data_count}")

    # Calculate log DPI
    df['Log_DPI'] = np.log(df[dpi_column])

    # Create a simple numeric index (since date analysis is not needed)
    df.index = range(1, len(df) + 1)

    # Step 6: Visualize the time series
    plt.figure(figsize=(12,6))
    plt.plot(df['Log_DPI'])
    plt.title('Log DPI Over Time')
    plt.xlabel('Observation Number')
    plt.ylabel('Log DPI')
    plt.show()

    # Interpretation of original series
    print("\nInterpretación de la Serie Original (Log DPI):")
    print(f"La gráfica muestra el logaritmo del Ingreso Personal Disponible ('{dpi_column}') a lo largo de {data_count} observaciones.")
    trend = df['Log_DPI'].diff().mean()
    if trend > 0:
        print("Se observa una tendencia al alza, indicando un crecimiento en el ingreso personal disponible.")
    elif trend < 0:
        print("Se observa una tendencia a la baja, indicando una disminución en el ingreso personal disponible.")
    else:
        print("No se observa una tendencia clara; el ingreso parece estable.")
    acf_vals = pd.Series(df['Log_DPI']).autocorr(lag=12)
    if abs(acf_vals) > 0.3:
        print("Hay indicios de un patrón estacional (posiblemente anual), debido a fluctuaciones regulares.")
    else:
        print("No se detecta un patrón estacional claro en los datos.")

    # Step 7: Stationarity test (Augmented Dickey-Fuller test)
    def adf_test(series, title=''):
        result = adfuller(series)
        output = []
        output.append(f'ADF Statistic ({title}): {result[0]:.4f}')
        output.append(f'p-value: {result[1]:.4f}')
        output.append(f'Critical Values: {result[4]}')
        if result[1] <= 0.05:
            output.append("Series is stationary")
        else:
            output.append("Series is not stationary - differencing may be needed")
        return '\n'.join(output), result[1]

    print("\nStationarity Test Results (Log DPI):")
    adf_result, adf_pvalue = adf_test(df['Log_DPI'], 'Log DPI')
    print(adf_result)

    # Interpretation of ADF test
    print("\nInterpretación de la Prueba ADF (Log DPI):")
    if adf_pvalue <= 0.05:
        print("La serie es estacionaria (p-valor <= 0.05), lo que indica que no tiene raíces unitarias.")
        print("No se requiere diferenciación adicional para el modelado ARIMA.")
    else:
        print("La serie no es estacionaria (p-valor > 0.05), sugiriendo la presencia de una raíz unitaria.")
        print("Se aplicará diferenciación para hacer la serie estacionaria.")

    # Calculate first difference if needed
    df['Log_DPI_diff'] = df['Log_DPI'].diff().dropna()
    print("\nStationarity Test Results (Differentiated Log DPI):")
    adf_diff_result, adf_diff_pvalue = adf_test(df['Log_DPI_diff'].dropna(), 'Differentiated Log DPI')
    print(adf_diff_result)

    # Interpretation of ADF test for differentiated series
    print("\nInterpretación de la Prueba ADF (Serie Diferenciada):")
    if adf_diff_pvalue <= 0.05:
        print("La serie diferenciada es estacionaria (p-valor <= 0.02), adecuada para modelado ARIMA.")
    else:
        print("La serie diferenciada aún no es estacionaria, lo cual es inusual. Considere más diferenciaciones o revisar los datos.")

    # Step 8: Plot ACF and PACF to determine p and q
    plt.figure(figsize=(12,4))
    plt.subplot(121)
    plot_acf(df['Log_DPI'], ax=plt.gca())
    plt.subplot(122)
    plot_pacf(df['Log_DPI'], ax=plt.gca())
    plt.show()

    # Interpretation of ACF and PACF
    print("\nInterpretación de las Funciones ACF y PACF:")
    acf_vals = pd.Series(acf(df['Log_DPI_diff'].dropna(), nlags=20))
    pacf_vals = pd.Series(pacf(df['Log_DPI_diff'].dropna(), nlags=20))
    acf_significant = np.where(np.abs(acf_vals[1:]) > 0.2)[0] + 1
    pacf_significant = np.where(np.abs(pacf_vals[1:]) > 0.2)[0] + 1
    print(f"Rezagos significativos en ACF: {acf_significant}")
    print(f"Rezagos significativos en PACF: {pacf_significant}")
    if len(pacf_significant) > 0 and pacf_significant[0] == 1:
        print("El primer rezago en PACF es significativo, sugiriendo un componente AR(1).")
    if len(acf_significant) > 0 and acf_significant[0] == 1:
        print("El primer rezago en ACF es significativo, sugiriendo un componente MA(1).")
    print("Basado en esto, se selecciona un modelo ARIMA(1,1,1) como punto de partida, considerando la diferenciación aplicada.")

    # Step 9: Fit ARIMA model (using 1,1,1 as example)
    model = ARIMA(df['Log_DPI'], order=(1,1,1))
    results = model.fit()

    # Print model summary
    print("\nModel Summary:")
    print(results.summary())

    # Interpretation of ARIMA model
    print("\nInterpretación del Modelo ARIMA(1,1,1):")
    ar_coef = results.arparams[0] if results.arparams.size > 0 else 0
    ma_coef = results.maparams[0] if results.maparams.size > 0 else 0
    print(f"Coeficiente AR(1): {ar_coef:.4f}, p-valor: {results.pvalues.get('ar.L1', 1):.4f}")
    print(f"Coeficiente MA(1): {ma_coef:.4f}, p-valor: {results.pvalues.get('ma.L1', 1):.4f}")
    if results.pvalues.get('ar.L1', 1) < 0.05:
        print("El término AR(1) es estadísticamente significativo (p-valor < 0.05), indicando que los valores pasados influyen en los actuales.")
    else:
        print("El término AR(1) no es significativo, sugiriendo que un modelo más simple podría ser adecuado.")
    if results.pvalues.get('ma.L1', 1) < 0.05:
        print("El término MA(1) es estadísticamente significativo (p-valor < 0.05), indicando que los errores pasados influyen en los actuales.")
    else:
        print("El término MA(1) no es significativo, sugiriendo que un modelo más simple podría ser adecuado.")
    print(f"AIC: {results.aic:.2f}. Un AIC más bajo indica un mejor ajuste del modelo; compare con otros modelos si es necesario.")

    # Step 10: Generate forecasts
    forecast_steps = 12  # Forecast 12 periods ahead
    forecast = results.forecast(steps=forecast_steps)

    # Plot actual vs forecast
    plt.figure(figsize=(12,6))
    plt.plot(df['Log_DPI'], label='Actual')
    forecast_index = range(len(df) + 1, len(df) + forecast_steps + 1)
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.title('Log DPI: Actual vs Forecast')
    plt.xlabel('Observation Number')
    plt.ylabel('Log DPI')
    plt.legend()
    plt.show()

    # Interpretation of forecast
    print("\nInterpretación de los Pronósticos:")
    print(f"La gráfica muestra los valores pronosticados para las próximas {forecast_steps} observaciones.")
    forecast_trend = pd.Series(forecast).diff().mean()
    if forecast_trend > 0:
        print("Los pronósticos muestran una tendencia al alza, sugiriendo un aumento en el ingreso personal disponible.")
    elif forecast_trend < 0:
        print("Los pronósticos muestran una tendencia a la baja, sugiriendo una disminución en el ingreso personal disponible.")
    else:
        print("Los pronósticos son relativamente estables, sin una tendencia clara.")
    print("La precisión de los pronósticos disminuye a medida que se extiende el horizonte, debido a la acumulación de incertidumbre.")

    # Calculate and print forecast values
    forecast_df = pd.DataFrame({'Forecast_Log_DPI': forecast}, index=forecast_index)
    print("\nForecast Values:")
    print(forecast_df)

    # Step 11: Calculate RMSE
    train_size = int(len(df) * 0.8)
    train, test = df['Log_DPI'][0:train_size], df['Log_DPI'][train_size:]
    model_test = ARIMA(train, order=(1,1,1))
    results_test = model_test.fit()
    predictions = results_test.forecast(steps=len(test))
    rmse = np.sqrt(np.mean((predictions - test) ** 2))
    print(f'\nRoot Mean Square Error (RMSE): {rmse}')

    # Interpretation of RMSE
    print("\nInterpretación del RMSE:")
    print(f"El RMSE de {rmse:.4f} mide el error promedio de las predicciones en la escala del Log DPI.")
    if rmse < df['Log_DPI'].std():
        print("El RMSE es menor que la desviación estándar de la serie, indicando un modelo razonablemente preciso.")
    else:
        print("El RMSE es alto en comparación con la variabilidad de la serie, sugiriendo que el modelo podría mejorarse.")
    print("Un RMSE más bajo indica mejor precisión; compare con otros modelos para evaluar el rendimiento.")

except KeyError as e:
    print(f"Error: {e}")
    print("Please check your column name and ensure it matches exactly (case-sensitive)")
except ValueError as e:
    print(f"Error: {e}")
    print("Please check if your DPI column contains valid numeric values")
except Exception as e:
    print(f"Unexpected error: {e}")
    print("Please verify your Excel file format and data")